trigger:
- '*'

pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: 'Release'

steps:
- task: UseDotNet@2
  displayName: 'use .net sdk 6.X'
  inputs:
    packageType: sdk
    version: '6.X'

- task: Npm@1
  displayName: 'Run npm install'
  inputs:
    verbose: false
- script: './node_modules/.bin/node-sass Tailspin.SpaceGame.Web/wwwroot --output Tailspin.SpaceGame.Web/wwwroot'
  displayName: 'Compile Sass assets'

- task: gulp@1
  displayName: 'Run gulp tasks'

- script: 'echo "$(Build.DefintionName), $(Build.BuildId), $(Build.BuildNumber)" > buuildinfo.txt'

- task: DotNetCoreCLI@2
  displayName: 'Restore project dependancies'
  inputs:
    comamnd: 'restore'
    projects: '**/*.csproj'

- task: DotNetCoreCLI@2
  displayName: 'Build the project - Release'
  inputs:
    command: 'build'
    arguments: '--no-restore --configuration Release'
    projects: '**/*csproj'